name: iStoreOS_x86_64_22.03

on: 
  workflow_dispatch:
    inputs:
          ssh_debug:
            description: "æ˜¯å¦å¼€å¯SSHè°ƒè¯•åŠŸèƒ½:"
            required: false
            default: "å…³é—­"
            type: choice
            options:
              - å…³é—­
              - å¼€å¯

          ssh_time1:
            description: "SSHè°ƒè¯•è®¾ç½®:å¼€å§‹ç¼–è¯‘å‰æš‚åœæ—¶é—´(åˆ†é’Ÿ):"
            required: false
            default: "30"
            type: string

          ssh_time2:
            description: "SSHè°ƒè¯•è®¾ç½®:ç¼–è¯‘æŠ¥é”™åæš‚åœæ—¶é—´(åˆ†é’Ÿ):"
            required: false
            default: "340"
            type: string

  schedule:
    - cron: 0 6 1,15 * *

env:
  BD_PROJECT: 'istoreos'       #é¡¹ç›®åç§°
  BD_TARGET: 'x86_64'        #ç¼–è¯‘ç›®æ ‡
  REPO_URL: 'https://github.com/istoreos/istoreos'  #é¡¹ç›®åœ°å€
  REPO_BRANCH: 'istoreos-22.03'  #é¡¹ç›®åˆ†æ”¯
  TARGET_PLATFORM: 'amd64'  #å¹³å°æ¶æ„(amd64/arm64)
  SSH_DEBUG: 'false' #æ˜¯å¦å¼€å¯SSHåŠŸèƒ½(true/false)
  SSH_TIME: '30'   #å•ä½åˆ†é’Ÿ,è®¾ç½®æš‚åœå·¥ä½œæµæ—¶é—´,å¯ç”¨pkill sleepå‘½ä»¤æå‰ç»§ç»­å·¥ä½œæµ,æ•´ä¸ªå·¥ä½œæµè¿è¡Œæ—¶é—´ä¸èƒ½è¶…è¿‡6å°æ—¶
  SSH_TIME2: '340'   #å•ä½åˆ†é’Ÿ,è®¾ç½®æš‚åœå·¥ä½œæµæ—¶é—´,å¯ç”¨pkill sleepå‘½ä»¤æå‰ç»§ç»­å·¥ä½œæµ,æ•´ä¸ªå·¥ä½œæµè¿è¡Œæ—¶é—´ä¸èƒ½è¶…è¿‡6å°æ—¶
  CACHE_CCACHE: 'false'    #æ˜¯å¦å¼€å¯ccacheåŠŸèƒ½(true/false)
  CACHE_CLEAN: 'false'     #æ˜¯å¦æ¸…é™¤ç¼“å­˜(true/false)
  UPLOAD_ARTIFACT: 'false'   #æ˜¯å¦ä¸Šä¼ åˆ°ARTIFACT(true/false)
  UPLOAD_RELEASE: 'true'    #æ˜¯å¦ä¸Šä¼ åˆ°RELEASE(true/false)


jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Check Server Performance
      run: |
        echo "è­¦å‘Šâš "
        echo "åˆ†é…çš„æœåŠ¡å™¨æ€§èƒ½æœ‰é™ï¼Œè‹¥é€‰æ‹©çš„æ’ä»¶è¿‡å¤šï¼ŒåŠ¡å¿…æ³¨æ„CPUæ€§èƒ½ï¼"
        echo -e "å·²çŸ¥CPUå‹å·(é™åº): 7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673\n"
        echo "--------------------------CPUä¿¡æ¯--------------------------"
        echo "CPUç‰©ç†æ•°é‡: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUæ ¸å¿ƒæ•°é‡: $(nproc)"
        echo -e "CPUå‹å·ä¿¡æ¯:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------å†…å­˜ä¿¡æ¯--------------------------"
        echo "å·²å®‰è£…å†…å­˜è¯¦ç»†ä¿¡æ¯:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt update
        sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
        sudo -E apt -y full-upgrade
        sudo -E apt-get -qq install btop build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils python3-pyelftools python3-setuptools libpython3-dev rsync unzip zlib1g-dev swig aria2 jq subversion qemu-utils ccache rename libelf-dev device-tree-compiler libgnutls28-dev coccinelle libgmp3-dev libmpc-dev libfuse-dev ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libc6-dev libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev libssl-dev libtool lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E systemctl daemon-reload
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name: Environment Customization
      run: |
        # åœ¨è¿™é‡Œå¯ä»¥æ ¹æ®é€‰æ‹©çš„ ssh_debug è¿›è¡Œç›¸åº”çš„ç¯å¢ƒè®¾ç½®
        if [ "${{ github.event.inputs.ssh_debug }}" == "å¼€å¯" ]; then
          # æ‰§è¡Œé’ˆå¯¹ å¼€å¯sshè°ƒè¯•åŠŸèƒ½ çš„ç¯å¢ƒè®¾ç½®æ“ä½œ
          echo "SSH_DEBUG=true" >> $GITHUB_ENV
          echo "SSH_TIME=${{ github.event.inputs.ssh_time1 }}" >> $GITHUB_ENV
          echo "SSH_TIME2=${{ github.event.inputs.ssh_time2 }}" >> $GITHUB_ENV
          echo "=====================å·²å¼€å¯SSHè°ƒè¯•åŠŸèƒ½===================="
          echo "==è®¾ç½®å¼€å§‹ç¼–è¯‘å‰æš‚åœ$(((${{ github.event.inputs.ssh_time1 }}) / 60))å°æ—¶$(((${{ github.event.inputs.ssh_time1 }}) % 60))åˆ†é’Ÿ,è‹¥ç¼–è¯‘æŠ¥é”™å°†ä¼šæš‚åœ$(((${{ github.event.inputs.ssh_time2 }}) / 60))å°æ—¶$(((${{ github.event.inputs.ssh_time2 }}) % 60))åˆ†é’Ÿ=="
          echo "==============å¯ä½¿ç”¨ gogogo å‘½ä»¤æå‰ç»§ç»­å·¥ä½œæµ============="
        else
          echo "=====================æœªå¼€å¯SSHè°ƒè¯•åŠŸèƒ½===================="
          echo "SSH_DEBUG=false" >> $GITHUB_ENV
        fi

    - name: Clone source code
      run: |
        git clone --depth 1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} ${{ env.BD_PROJECT }}
        
    - name: Free up disk space
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p -m 777 /mnt/${{ env.BD_PROJECT }}/dl /mnt/${{ env.BD_PROJECT }}/bin /mnt/${{ env.BD_PROJECT }}/staging_dir /mnt/${{ env.BD_PROJECT }}/build_dir
        ln -sf /mnt/${{ env.BD_PROJECT }}/dl ${{ env.BD_PROJECT }}/dl
        ln -sf /mnt/${{ env.BD_PROJECT }}/bin ${{ env.BD_PROJECT }}/bin
        ln -sf /mnt/${{ env.BD_PROJECT }}/staging_dir ${{ env.BD_PROJECT }}/staging_dir
        ln -sf /mnt/${{ env.BD_PROJECT }}/build_dir ${{ env.BD_PROJECT }}/build_dir
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Cache
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: ${{ env.CACHE_CCACHE }}
        mixkey: ${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}_${{ env.REPO_BRANCH }}
        clean: ${{ env.CACHE_CLEAN }}
        prefix: ${{ github.workspace }}/${{ env.BD_PROJECT }}
        
    - name: Update & Install feeds
      working-directory: ./${{ env.BD_PROJECT }}
      run: |
        mv $GITHUB_WORKSPACE/feeds/${{ env.BD_PROJECT }}_${{ env.BD_TARGET }} $GITHUB_WORKSPACE/${{ env.BD_PROJECT }}/feeds.conf
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        chmod +x $GITHUB_WORKSPACE/customize/*.sh
        $GITHUB_WORKSPACE/customize/${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}.sh
        $GITHUB_WORKSPACE/customize/preset-adguard-core.sh ${{ env.TARGET_PLATFORM }}
        $GITHUB_WORKSPACE/customize/preset-clash-core.sh ${{ env.TARGET_PLATFORM }}

    - name: "Configuration Customization - Build_${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}"
      env:
        CONFIG_FILE: './config/${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ${{ env.BD_PROJECT }}/.config
        cd ${{ env.BD_PROJECT }}
        sudo echo "cd $PWD" >> /home/runner/.bashrc
        [ "${{ env.CACHE_CCACHE }}" == 'true' ] && echo -e 'CONFIG_CCACHE=y' >> .config
        make defconfig

    - name: Setup ssh for debug 
      if: env.SSH_DEBUG == 'true'
      continue-on-error: true
      run: |
        # å…è®¸rootç™»å½•å¹¶è®¾ç½®rootå¯†ç 
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config 
        if [ -n "${{ secrets.SSH_PW }}" ]; then
          echo "root:${{ secrets.SSH_PW }}" | sudo chpasswd
        else
          echo "root:123" | sudo chpasswd
        fi
    
        # é‡å¯SSHæœåŠ¡
        sudo service sshd restart
    
        # é…ç½®å’Œå¯åŠ¨frpc
        if [ -n "${{ secrets.FRPC_CONFIG }}" ]; then
          # ä½¿ç”¨æä¾›çš„frpcé…ç½®
          echo "${{ secrets.FRPC_CONFIG }}" > ./frpc.ini
          chmod +x ./frpc && ./frpc -c ./frpc.ini > ./frpc.log 2>&1 &
          sleep 5
          if grep -q "start proxy success" ./frpc.log; then
            echo "================frpcå¯åŠ¨æˆåŠŸ!================"
            echo "=========æ£€æµ‹ä¸ºè‡ªå®šä¹‰é…ç½®,è¯·è‡ªè¡Œè¿æ¥SSH========="
            echo "SSH_SETUP=success" >> $GITHUB_ENV
          else
            echo "è­¦å‘Š:å°è¯•å¯åŠ¨frpcå¤±è´¥ã€‚è¯·é‡æ–°é…ç½®FRPC_CONFIGå­—æ®µ"
            echo "==================ç»§ç»­å·¥ä½œæµ==================="
            echo "SSH_SETUP=failure" >> $GITHUB_ENV
          fi
        else
          # ç”Ÿæˆéšæœºç«¯å£å¹¶é…ç½®frpc
          max_attempts=10
          attempts=0

          while [ $attempts -lt $max_attempts ]; do
            random_port=$(shuf -i 10001-50000 -n 1)
            cp frpc.ini.example frpc.ini
            sed -i "s/\[ssh2action\]/\[ssh2action$random_port\]/g" frpc.ini
            sed -i "s/remote_port = 22222/remote_port = $random_port/g" frpc.ini
            chmod +x ./frpc && ./frpc -c ./frpc.ini > ./frpc.log 2>&1 &
            sleep 5
            # æ£€æŸ¥frpcå¯åŠ¨é”™è¯¯
            if grep -q "start proxy success" ./frpc.log; then
              echo "============frpcå¯åŠ¨æˆåŠŸ!============"
              echo "==========ä»¥ä¸‹æ˜¯SSHè¿æ¥å‘½ä»¤==========="
              echo "ssh root@$(grep -E 'server_addr\s*=' frpc.ini | cut -d'=' -f2 | tr -d '[:space:]') -p $random_port"
              echo "===================================="
              echo "SSH_SETUP=success" >> $GITHUB_ENV
              break
            else
              echo "é”™è¯¯:frpcå¯åŠ¨å¤±è´¥!é‡è¯•ä¸­..."
              pkill frpc
              attempts=$((attempts+1))
            fi
          done

          if [ $attempts -eq $max_attempts ]; then
              echo "è­¦å‘Š:å°è¯•å¯åŠ¨frpc $max_attempts æ¬¡ä»ç„¶å¤±è´¥ã€‚è¯·è‡ªè¡Œé…ç½®FRPC_CONFIGå­—æ®µ"
              echo "======================ç»§ç»­å·¥ä½œæµ======================="
              echo "SSH_SETUP=failure" >> $GITHUB_ENV
          fi
        fi
        
    - name: Pause workflow for custom
      if: env.SSH_DEBUG == 'true' && env.SSH_SETUP == 'success'
      run: |
        # åŠ è½½gogogoå‘½ä»¤
        source $GITHUB_WORKSPACE/customize/diy/gogogo.sh
        echo "===================å·²æš‚åœå·¥ä½œæµ==================="      # å€’è®¡æ—¶å¾ªç¯
        count=0
        while [ ! -f /home/runner/stop_signal ] && [ $count -lt $((60 * ${{ env.SSH_TIME }})) ] ; do
          sleep 1
          count=$((count + 1))
        done
        echo "å·²è¿‡æ—¶é—´ï¼š$((count / 60))åˆ†é’Ÿ$((count % 60))ç§’"
        # å¾ªç¯ç»“æŸååˆ é™¤æ–‡ä»¶
        sudo rm -f /home/runner/stop_signal
        
    - name: Download package
      working-directory: ./${{ env.BD_PROJECT }}
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Build firmware
      working-directory: ./${{ env.BD_PROJECT }}
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) || make -j1 V=s | tee build.log
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Check compile
      run: |
        # åŠ è½½æ¶ˆæ¯é€šçŸ¥åŠŸèƒ½
        send_message() {
          if [ -n "${{ secrets.IYUU_TOKEN }}" ]; then
            # å‘é€æ¶ˆæ¯åˆ° IYUU æ¥å£
            curl -X POST \
            "https://iyuu.cn/${{ secrets.IYUU_TOKEN }}.send" \
            -H 'Content-Type: application/json' \
            -d '{"text": "'"${1}"'", "desp": "'"${2}"'"}' > /dev/null 2>&1
            echo "=======å·²é€šè¿‡IYUUæ¥å£å‘é€é€šçŸ¥======="
          fi
      
          if [ -n "${{ secrets.SERVERCHAN_SCKEY }}" ]; then
            # å‘é€æ¶ˆæ¯åˆ° Serveré…±
            curl -X POST \
            "https://sc.ftqq.com/${{ secrets.SERVERCHAN_SCKEY }}.send" \
            -H 'Content-Type: application/json;charset=utf-8' \
            -d '{"text": "'"${1}"'", "desp": "'"${2}"'"}' > /dev/null 2>&1
            echo "=======å·²é€šè¿‡Serveré…±å‘é€é€šçŸ¥======="
          fi
        }

        cd ${{ env.BD_PROJECT }}/bin/targets/*/*
        if [ -n "$(ls *.img.gz)" ]; then
          echo "BD_COMPILE=success" >> $GITHUB_ENV
          echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
          echo "DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
          echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
          uppercase_string=$(echo "${{ env.BD_PROJECT }}" | tr '[:lower:]' '[:upper:]')
          echo "Uppercase_String=$uppercase_string" >> $GITHUB_ENV
          tar -czvf packages.tar.gz packages
          rm -rf packages
          echo "===========ç¼–è¯‘æˆåŠŸ,å‡†å¤‡ä¸Šä¼ ==========="
        else
          if [ "${{ env.SSH_SETUP }}" == 'success' ]; then
            echo "BD_COMPILE=standby" >> $GITHUB_ENV
            echo "===========ç¼–è¯‘å¤±è´¥,æš‚åœå·¥ä½œæµ==========="
            send_message "ç¼–è¯‘å¤±è´¥" "ç¼–è¯‘å¤±è´¥,å·²æš‚åœå·¥ä½œæµ,è¯·ä½¿ç”¨SSHç™»å½•è°ƒè¯•"
          else
            echo "===========ç¼–è¯‘å¤±è´¥,ç»“æŸå·¥ä½œæµ==========="
            exit 1
          fi        
        fi

    - name: Pause workflow for debug 
      if: env.BD_COMPILE == 'standby'
      run: |
        # åŠ è½½gogogoå‘½ä»¤
        source $GITHUB_WORKSPACE/customize/diy/gogogo.sh

        # åŠ è½½æ¶ˆæ¯é€šçŸ¥åŠŸèƒ½
        send_message() {
          if [ -n "${{ secrets.IYUU_TOKEN }}" ]; then
            # å‘é€æ¶ˆæ¯åˆ° IYUU æ¥å£
            curl -X POST \
            "https://iyuu.cn/${{ secrets.IYUU_TOKEN }}.send" \
            -H 'Content-Type: application/json' \
            -d '{"text": "'"${1}"'", "desp": "'"${2}"'"}' > /dev/null 2>&1
            echo "=======å·²é€šè¿‡IYUUæ¥å£å‘é€é€šçŸ¥======="
          fi
      
          if [ -n "${{ secrets.SERVERCHAN_SCKEY }}" ]; then
            # å‘é€æ¶ˆæ¯åˆ° Serveré…±
            curl -X POST \
            "https://sc.ftqq.com/${{ secrets.SERVERCHAN_SCKEY }}.send" \
            -H 'Content-Type: application/json;charset=utf-8' \
            -d '{"text": "'"${1}"'", "desp": "'"${2}"'"}' > /dev/null 2>&1
            echo "=======å·²é€šè¿‡Serveré…±å‘é€é€šçŸ¥======="
          fi
        }
        
        # åŠ è½½ç¼–è¯‘ç»“æœæ£€æŸ¥åŠŸèƒ½
        check_compile() {
          cd ${{ env.BD_PROJECT }}/bin/targets/*/*
          if [ -n "$(ls *.img.gz)" ]; then
            echo "BD_COMPILE=success" >> $GITHUB_ENV
            echo "FIRMWARE_PATH=$PWD" >> $GITHUB_ENV
            echo "DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
            KERNEL=$(cat *.manifest | awk '/^kernel/ {print $2}' | tr -d ' ')
            echo "KERNEL=$KERNEL" >> $GITHUB_ENV
            Uppercase_String=$(echo "${{ env.BD_PROJECT }}" | tr '[:lower:]' '[:upper:]')
            echo "Uppercase_String=$Uppercase_String" >> $GITHUB_ENV
            tar -czvf packages.tar.gz packages
            rm -rf packages
            echo "===========ç¼–è¯‘æˆåŠŸ,å‡†å¤‡ä¸Šä¼ ==========="
            send_message "ç¼–è¯‘æˆåŠŸ,å‡†å¤‡ä¸Šä¼ " "ç¼–è¯‘æˆåŠŸ,å‡†å¤‡ä¸Šä¼ "
          else
            rm -f /home/runner/stop_signal
            echo "===========ç¼–è¯‘å¤±è´¥,ç»§ç»­æš‚åœ==========="
            echo "BD_COMPILE=failure" >> $GITHUB_ENV
            send_message "ç¼–è¯‘å¤±è´¥,ç»§ç»­æš‚åœ" "ç¼–è¯‘å¤±è´¥,ç»§ç»­æš‚åœ"
            return 1  # è¿”å›éé›¶å€¼è¡¨ç¤ºç¼–è¯‘å¤±è´¥
          fi
        }

        # è¾“å‡ºæ¶ˆæ¯
        echo "====================æš‚åœå·¥ä½œæµ===================="
        echo "==========å¯ä½¿ç”¨ gogogo å‘½ä»¤æå‰ç»§ç»­å·¥ä½œæµ=========="
        if [ -n "${{ secrets.IYUU_TOKEN }}" ] || [ -n "${{ secrets.SERVERCHAN_SCKEY }}" ]; then
          echo "æ¨èmake -j$(nproc) ; gogogo ç¼–è¯‘ï¼Œæ‰§è¡Œå®Œæˆä¼šé€šè¿‡ çˆ±è¯­é£é£ æˆ–è€… Serveré…± è¿›è¡Œé€šçŸ¥"
        fi

        # å€’è®¡æ—¶,åˆå§‹åŒ–å†…éƒ¨è®¡æ•°å™¨ï¼Œç”¨äºæ§åˆ¶å¾ªç¯æ¬¡æ•°
        count=0 
        while [ $count -lt $((60 * ${{ env.SSH_TIME2 }})) ] ; do
          # æ¯ç§’é’Ÿå¢åŠ å†…éƒ¨è®¡æ•°å™¨
          while [ ! -f /home/runner/stop_signal ] && [ $count -lt $((60 * ${{ env.SSH_TIME2 }})) ]; do
            sleep 1
            count=$((count + 1))        
          done
          echo -ne "\033[0Kå·²è¿‡æ—¶é—´ï¼š$((count / 60))åˆ†é’Ÿ$((count % 60))ç§’. \r"
          cd $GITHUB_WORKSPACE
          check_compile && break
        done

        # å¤„ç†ç¼–è¯‘å¤±è´¥
        if [ "${{ env.BD_COMPILE }}" == 'failure' ]; then
          exit 1
        fi

    
    - name: Upload Firmware To Release
      if: env.BD_COMPILE == 'success' && env.UPLOAD_RELEASE == 'true'
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.DATE }}_${{ env.Uppercase_String }}_${{ env.BD_TARGET }}_${{ env.REPO_BRANCH }}
        allowUpdates: true
        tag: ${{ env.DATE }}_${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}_${{ env.REPO_BRANCH }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE_PATH }}/*
        body: |
          ===Firmware ${{ env.Uppercase_String }} for ${{ env.BD_TARGET }}===
          ### ğŸ“’ å›ºä»¶ä¿¡æ¯
          - ğŸ’» å¹³å°æ¶æ„: ${{ env.BD_TARGET }}
          - âš½ å›ºä»¶æºç : ${{ env.REPO_URL }}
          - ğŸ’ æºç åˆ†æ”¯: ${{ env.REPO_BRANCH }}
          - ğŸš€ å†…æ ¸ç‰ˆæœ¬: ${{ env.KERNEL }}
          - ğŸŒ é»˜è®¤åœ°å€: 10.1.1.254
          - ğŸ”‘ é»˜è®¤å¯†ç : ç©º                

          ### ğŸ“’ æ’ä»¶åˆ—è¡¨:
          ```
          DockerMan
          PassWall
          Openclash
          Autotimeset
          AdGuardHome
          Netdata
          DDNS-go
          ZeroTier
          åº”ç”¨ä¸­å¿ƒ(iStore)
          ```

    - name: Organize files
      if: env.BD_COMPILE == 'success' && env.UPLOAD_ARTIFACT == 'true'
      working-directory: ${{ env.FIRMWARE_PATH }}
      run: |
        echo "=============ç”Ÿæˆæ–‡ä»¶åˆ—è¡¨============="
        ls -lh | awk '{print $9, $5}'
        echo "==============æ¸…ç†æ–‡ä»¶ä¸­============="
        rm -rf *kernel.bin *rootfs* *.json *.tar.zst
        sleep 2
        echo "=============ä¸Šä¼ æ–‡ä»¶åˆ—è¡¨============="
        ls -lh | awk '{print $9, $5}'
        echo "===================================="

    - name : Upload artifact
      uses: actions/upload-artifact@main
      if: env.BD_COMPILE == 'success' && env.UPLOAD_ARTIFACT == 'true'
      with:
        name: ${{ env.BD_PROJECT }}-firmware-${{ env.BD_TARGET }}-${{ env.DATE }}
        path: ${{ env.FIRMWARE_PATH }} 
        retention-days: 2

    - name: Check Disk
      continue-on-error: true
      run: |
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
