name: test

on: 
  repository_dispatch:
  workflow_dispatch:

env:
  BD_PROJECT: 'istoreos'       #é¡¹ç›®åç§°
  BD_TARGET: 'x86_64'        #ç¼–è¯‘ç›®æ ‡
  REPO_URL: 'https://github.com/istoreos/istoreos'  #é¡¹ç›®åœ°å€
  REPO_BRANCH: 'istoreos-22.03'  #é¡¹ç›®åˆ†æ”¯
  TARGET_PLATFORM: 'amd64'  #å¹³å°æ¶æ„(amd64/arm64)
  SSH_DEBUG: 'true'  #æ˜¯å¦å¼€å¯SSHåŠŸèƒ½(true/false)
  SSH_TIME: '340'   #å•ä½åˆ†é’Ÿ,è®¾ç½®æš‚åœå·¥ä½œæµæ—¶é—´,å¯ç”¨pkill sleepå‘½ä»¤æå‰ç»§ç»­å·¥ä½œæµ,æ•´ä¸ªå·¥ä½œæµè¿è¡Œæ—¶é—´ä¸èƒ½è¶…è¿‡6å°æ—¶
  CACHE_CCACHE: 'false'    #æ˜¯å¦å¼€å¯ccacheåŠŸèƒ½(true/false)
  CACHE_CLEAN: 'false'     #æ˜¯å¦æ¸…é™¤ç¼“å­˜(true/false)
  UPLOAD_ARTIFACT: 'true'   #æ˜¯å¦ä¸Šä¼ åˆ°ARTIFACT(true/false)
  UPLOAD_RELEASE: 'false'    #æ˜¯å¦ä¸Šä¼ åˆ°RELEASE(true/false)

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Check Server Performance
      run: |
        echo "è­¦å‘Šâš "
        echo "åˆ†é…çš„æœåŠ¡å™¨æ€§èƒ½æœ‰é™ï¼Œè‹¥é€‰æ‹©çš„æ’ä»¶è¿‡å¤šï¼ŒåŠ¡å¿…æ³¨æ„CPUæ€§èƒ½ï¼"
        echo -e "å·²çŸ¥CPUå‹å·(é™åº): 7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673\n"
        echo "--------------------------CPUä¿¡æ¯--------------------------"
        echo "CPUç‰©ç†æ•°é‡: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUæ ¸å¿ƒæ•°é‡: $(nproc)"
        echo -e "CPUå‹å·ä¿¡æ¯:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------å†…å­˜ä¿¡æ¯--------------------------"
        echo "å·²å®‰è£…å†…å­˜è¯¦ç»†ä¿¡æ¯:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT


    - name: Clone source code
      run: |
        git clone --depth 1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} ${{ env.BD_PROJECT }}

    - name: Free up disk space
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p -m 777 /mnt/${{ env.BD_PROJECT }}/dl /mnt/${{ env.BD_PROJECT }}/bin /mnt/${{ env.BD_PROJECT }}/staging_dir /mnt/${{ env.BD_PROJECT }}/build_dir
        ln -sf /mnt/${{ env.BD_PROJECT }}/dl ${{ env.BD_PROJECT }}/dl
        ln -sf /mnt/${{ env.BD_PROJECT }}/bin ${{ env.BD_PROJECT }}/bin
        ln -sf /mnt/${{ env.BD_PROJECT }}/staging_dir ${{ env.BD_PROJECT }}/staging_dir
        ln -sf /mnt/${{ env.BD_PROJECT }}/build_dir ${{ env.BD_PROJECT }}/build_dir
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Cache
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: ${{ env.CACHE_CCACHE }}
        mixkey: ${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}_${{ env.REPO_BRANCH }}
        clean: ${{ env.CACHE_CLEAN }}
        prefix: ${{ github.workspace }}/${{ env.BD_PROJECT }}
        
    - name: Update & Install feeds
      working-directory: ./${{ env.BD_PROJECT }}
      run: |
        mv $GITHUB_WORKSPACE/feeds/${{ env.BD_PROJECT }}_${{ env.BD_TARGET }} $GITHUB_WORKSPACE/${{ env.BD_PROJECT }}/feeds.conf
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        chmod +x $GITHUB_WORKSPACE/customize/*.sh
        $GITHUB_WORKSPACE/customize/${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}.sh
        $GITHUB_WORKSPACE/customize/preset-adguard-core.sh ${{ env.TARGET_PLATFORM }}
        $GITHUB_WORKSPACE/customize/preset-clash-core.sh ${{ env.TARGET_PLATFORM }}
        
    - name: "Configuration Customization - Build_${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}"
      env:
        CONFIG_FILE: './config/${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ${{ env.BD_PROJECT }}/.config
        cd ${{ env.BD_PROJECT }}
        sudo echo "cd $PWD" >> /home/runner/.bashrc
        [ "${{ env.CACHE_CCACHE }}" == 'true' ] && echo -e 'CONFIG_CCACHE=y' >> .config
        make defconfig

    - name: Setup ssh for debug 
      if: env.SSH_DEBUG == 'true'
#      continue-on-error: true  
      run: |
        # å…è®¸rootç™»å½•å¹¶è®¾ç½®rootå¯†ç 
        echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config 
        if [ -n "${{ secrets.SSH_PW }}" ]; then
          echo "root:${{ secrets.SSH_PW }}" | sudo chpasswd
        else
          echo "root:123" | sudo chpasswd
        fi
    
        # é‡å¯SSHæœåŠ¡
        sudo service sshd restart
    
        # é…ç½®å’Œå¯åŠ¨frpc
        if [ -n "${{ secrets.FRPC_CONFIG }}" ]; then
          # ä½¿ç”¨æä¾›çš„frpcé…ç½®
          echo "${{ secrets.FRPC_CONFIG }}" > ./frpc.ini
          chmod +x ./frpc && ./frpc -c ./frpc.ini > ./frpc.log 2>&1 &
          sleep 5
          if grep -q "start proxy success" ./frpc.log; then
            echo "================frpcå¯åŠ¨æˆåŠŸ!================"
            echo "=========æ£€æµ‹ä¸ºè‡ªå®šä¹‰é…ç½®,è¯·è‡ªè¡Œè¿æ¥SSH========="
            echo "SSH_SETUP=success" >> $GITHUB_ENV
          else
            echo "è­¦å‘Š:å°è¯•å¯åŠ¨frpcå¤±è´¥ã€‚è¯·é‡æ–°é…ç½®FRPC_CONFIGå­—æ®µ"
            echo "==================ç»“æŸå·¥ä½œæµ==================="
            echo "SSH_SETUP=failure" >> $GITHUB_ENV
            exit 1
          fi
        else
          # ç”Ÿæˆéšæœºç«¯å£å¹¶é…ç½®frpc
          max_attempts=10
          attempts=0

          while [ $attempts -lt $max_attempts ]; do
            random_port=$(shuf -i 10001-50000 -n 1)
            cp frpc.ini.example frpc.ini
            sed -i "s/\[ssh2action\]/\[ssh2action$random_port\]/g" frpc.ini
            sed -i "s/remote_port = 22222/remote_port = $random_port/g" frpc.ini
            chmod +x ./frpc && ./frpc -c ./frpc.ini > ./frpc.log 2>&1 &
            sleep 5
            # æ£€æŸ¥frpcå¯åŠ¨é”™è¯¯
            if grep -q "start proxy success" ./frpc.log; then
              echo "============frpcå¯åŠ¨æˆåŠŸ!============"
              echo "==========ä»¥ä¸‹æ˜¯SSHè¿æ¥å‘½ä»¤==========="
              echo "ssh root@$(grep -E 'server_addr\s*=' frpc.ini | cut -d'=' -f2 | tr -d '[:space:]') -p $random_port"
              echo "===================================="
              echo "SSH_SETUP=success" >> $GITHUB_ENV
              break
            else
              echo "é”™è¯¯:frpcå¯åŠ¨å¤±è´¥!é‡è¯•ä¸­..."
              pkill frpc
              attempts=$((attempts+1))
            fi
          done

          if [ $attempts -eq $max_attempts ]; then
            echo "è­¦å‘Š:å°è¯•å¯åŠ¨frpc $max_attempts æ¬¡ä»ç„¶å¤±è´¥ã€‚è¯·è‡ªè¡Œé…ç½®FRPC_CONFIGå­—æ®µ"
            echo "======================ç»“æŸå·¥ä½œæµ======================="
            echo "SSH_SETUP=failure" >> $GITHUB_ENV
            exit 1
          fi
        fi

    - name: Pause workflow
      if: env.SSH_DEBUG == 'true'
      run: |
        # åŠ è½½gogogoå‘½ä»¤
        sudo echo '
        function gogogo() {
        touch ~/stop_signal
        }
        ' >> /etc/bash.bashrc
        # å¼•å…¥å‡½æ•°åº“
        source $GITHUB_WORKSPACE/customize/diy/functions.sh
        # è¾“å‡ºæ¶ˆæ¯
        echo "====================æš‚åœå·¥ä½œæµ===================="
        if [ -n "${{ secrets.IYUU_TOKEN }}" ] || [ -n "${{ secrets.SERVERCHAN_SCKEY }}" ]; then
          echo -n -e "æ¨èmake -j$(nproc) ; gogogo ç¼–è¯‘ï¼Œæ‰§è¡Œå®Œæˆä¼šå¾®ä¿¡é€šçŸ¥"
        fi

        # å€’è®¡æ—¶,åˆå§‹åŒ–å†…éƒ¨è®¡æ•°å™¨ï¼Œç”¨äºæ§åˆ¶å¾ªç¯æ¬¡æ•°
        count=0 

        # åœ¨æœªæ”¶åˆ°åœæ­¢ä¿¡å·ä¸”å†…éƒ¨è®¡æ•°å™¨æœªè¾¾åˆ°è®¾å®šçš„æ—¶é—´é™åˆ¶æ—¶ï¼Œæ‰§è¡Œå¾ªç¯
        while [ ! -f ~/stop_signal ] && [ $count -lt $((60 * ${{ env.SSH_TIME }})) ]; do
          echo -n -e "å·²è¿‡æ—¶é—´ï¼š$((count / 60))åˆ†é’Ÿ$((count % 60))ç§’ï¼Œå¯ä½¿ç”¨gogogoå‘½ä»¤æå‰ç»§ç»­å·¥ä½œæµ! \033[0K\r"
          # æ£€æŸ¥ç¼–è¯‘ç»“æœ
          check_compile_result
          # æ¯ç§’é’Ÿå¢åŠ å†…éƒ¨è®¡æ•°å™¨
          sleep 1
          count=$((count + 1))
        done

        # å¤„ç†ç¼–è¯‘å¤±è´¥
        if [ "${{ env.BD_COMPILE }}" == 'failure' ]; then
          exit 1
        fi

    # - name: Upload Firmware To Release
    #   if: env.BD_COMPILE == 'success' && env.UPLOAD_RELEASE == 'true'
    #   uses: ncipollo/release-action@main
    #   with:
    #     name: ${{ env.DATE }}_${{ env.Uppercase_String }}_${{ env.BD_TARGET }}_${{ env.REPO_BRANCH }}
    #     allowUpdates: true
    #     tag: ${{ env.BD_PROJECT }}_${{ env.BD_TARGET }}_${{ env.REPO_BRANCH }}
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     artifacts: ${{ env.FIRMWARE_PATH }}/*
    #     body: |
    #       ===Firmware ${{ env.Uppercase_String }} for ${{ env.BD_TARGET }}===
    #       ### ğŸ“’ å›ºä»¶ä¿¡æ¯
    #       - ğŸ’» å¹³å°æ¶æ„: ${{ env.BD_TARGET }}
    #       - âš½ å›ºä»¶æºç : ${{ env.REPO_URL }}
    #       - ğŸ’ æºç åˆ†æ”¯: ${{ env.REPO_BRANCH }}
    #       - ğŸš€ å†…æ ¸ç‰ˆæœ¬: ${{ env.KERNEL }}
    #       - ğŸŒ é»˜è®¤åœ°å€: 10.1.1.254
    #       - ğŸ”‘ é»˜è®¤å¯†ç : ç©º       

    #       ### ğŸ“’ æ’ä»¶åˆ—è¡¨:
    #       ```
    #       ShadowSocksR Plus+
    #       PassWall
    #       Openclash
    #       Netdata
    #       Autotimeset
    #       AdGuard Home
    #       Mosdns
    #       DDNS-go
    #       ZeroTier
    #       Openvpn
    #       åº”ç”¨ä¸­å¿ƒ(iStore)
    #       ```

    - name: Organize files
      if: env.BD_COMPILE == 'success' && env.UPLOAD_ARTIFACT == 'true'
      working-directory: ${{ env.FIRMWARE_PATH }}
      run: |
        echo "=============ç”Ÿæˆæ–‡ä»¶åˆ—è¡¨============="
        ls -lh | awk '{print $9, $5}'
        echo "==============æ¸…ç†æ–‡ä»¶ä¸­============="
        rm -rf *kernel.bin *rootfs* *.json *.tar.zst
        sleep 2
        echo "=============ä¸Šä¼ æ–‡ä»¶åˆ—è¡¨============="
        ls -lh | awk '{print $9, $5}'
        echo "===================================="

    - name : Upload artifact
      uses: actions/upload-artifact@main
      if: env.BD_COMPILE == 'success' && env.UPLOAD_ARTIFACT == 'true'
      with:
        name: ${{ env.BD_PROJECT }}-firmware-${{ env.BD_TARGET }}-${{ env.DATE }}
        path: ${{ env.FIRMWARE_PATH }} 
        retention-days: 2

    - name: Check Disk
      continue-on-error: true
      run: |
        echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
        echo "ç¡¬ç›˜æ•°é‡: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
